#!/bin/sh

# This bootstrap is suitable for Debian 12.
#

# Add Debian backports.
export DEBIAN_CODENAME=$( . /etc/os-release && echo $VERSION_CODENAME )
echo "deb http://deb.debian.org/debian ${DEBIAN_CODENAME}-backports main" | sudo tee /etc/apt/sources.list.d/${DEBIAN_CODENAME}-backports.list

# Update yadm repo origin URL.
yadm remote set-url origin "git@github.com:sleeping-miyagi/dotfiles.git"

# Add contrib and non-free-firmware repositories
sudo apt update -y
sudo apt upgrade -y
sudo apt install software-properties-common -y
sudo apt-add-repository contrib non-free-firmware -y
sudo apt update

# Install window manager, sound server, display server.
sudo apt install xinit pipewire i3 -y

# Install fonts.
sudo apt install fonts-noto fonts-fantasque-sans fonts-liberation2 -y

# Install background services.
sudo apt install dex dunst feh xsettingsd gnome-themes-extra lxpolkit -y

# Install additional system utilities.
sudo apt install pavucontrol arandr xclip maim htop neofetch rclone fcitx5 fcitx5-mozc zenity -y

# Install flatpak and flatpak repo
sudo apt install flatpak
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

# Install apps and programs.
sudo apt install pass vim chromium webext-ublock-origin-chromium nnn sxiv zathura xournal mpv yt-dlp/${DEBIAN_CODENAME}-backports ytfzf mutt-wizard pandoc texlive-xetex cmus -y

# Add home directories
mkdir -p ~/documents ~/downloads ~/music ~/pictures ~/videos ~/public

# Build and install custom st.
sudo apt install libharfbuzz-dev libxft-dev libxext-dev build-essential -y
git clone https://github.com/sleeping-miyagi/st
cd st
sudo make install
cd ..
rm -rf st

# Build and install custom dmenu.
sudo apt install libxinerama-dev -y
git clone https://github.com/sleeping-miyagi/dmenu
cd dmenu
sudo make install
cd ..
rm -rf dmenu

# Build and install pam_gnupg
sudo apt install automake libtool libpam0g-dev -y
git clone https://github.com/cruegge/pam-gnupg
cd pam-gnupg
./autogen.sh
./configure
make
sudo make install
cd ..
rm -rf pam-gnupg

PAMDLOGIN="/etc/pam.d/login"
PAMGNUPGLINE1="auth     optional  pam_gnupg.so store-only"
PAMGNUPGLINE2="session  optional  pam_gnupg.so"

if ! grep -Fxq "$PAMGNUPGLINE1" $PAMDLOGIN
then
    echo "$PAMGNUPGLINE1" | sudo tee -a $PAMDLOGIN
fi

if ! grep -Fxq "$PAMGNUPGLINE2" $PAMDLOGIN
then
    echo "$PAMGNUPGLINE2" | sudo tee -a $PAMDLOGIN
fi
